apiVersion: v1
kind: Service
metadata:
  name: dnssec-service-mysql-signer-customer-01
  namespace: customer-01
  labels:
    app: dnssec-mysql-customer-01
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: dnssec-mysql-customer-01
  clusterIP: None
