apiVersion: v1
kind: LimitRange
metadata:
  name: dnssec-limit-range-customer-01
  namespace: customer-01
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 1
    max:
      memory: 512Mi
      cpu: 2
    min:
      memory: 256Mi
      cpu: 1
    type: Container