kind: Service
apiVersion: v1
metadata:
  name: dnssec-service-dns
  namespace: customer-01
spec:
  selector:
    app: dnssec-deployment-customer-01
  type: NodePort 
  ports:
    - name: dns-udp
      port: 5001 # 5002, 5003, etc. Internal port for the service inside the cluster
      targetPort: 53 # real port on pod
      nodePort: 30100 # Port for external access
      protocol: UDP
    - name: dns-tcp
      port: 5001 # 5002, 5003, etc. Internal port for the service inside the cluster
      targetPort: 53 # real port on pod
      nodePort: 30100 # Port for external access
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: dnssec-service-http
  namespace: customer-01
spec:
  selector:
    app: dnssec-deployment-customer-01
  ports:
    - name: http-80
      port: 5002 
      targetPort: 8081 # PDNS API



# 30000 - 32767     
# mysql-service.shared-mysql.svc.cluster.local
# https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-organizing-with-namespaces
