apiVersion: v1
kind: ConfigMap
metadata:
  name: dnssec-configmap-customer-01
  namespace: customer-01
data:
  SIGNER_MYSQL_HOST: dnssec-service-mysql-signer-customer-01 # MySQL internal service name
  SIGNER_MYSQL_USER: opendnssec
  SIGNER_MYSQL_DATABASE: opendnssec
  SIGNER_MYSQL_PORT: "3306"

  
  # OPENDNSSEC
  #SIGNER_SHM_LABEL: OpenDNSSEC
  SIGNER_ADAPTER_DNS_TSIG_IN_NAME: nsd_master
  SIGNER_ADAPTER_DNS_TSIG_IN_ALGORITHM: hmac-sha256
  SIGNER_ADAPTER_DNS_TSIG_IN_SECRET: "TlNEX1RTSUdfU0VDUkVUX0tFWQo="
  SIGNER_ADAPTER_DNS_TSIG_OUT_NAME: nsd_slave
  SIGNER_ADAPTER_DNS_TSIG_OUT_ALGORITHM: hmac-sha256
  SIGNER_ADAPTER_DNS_TSIG_OUT_SECRET: "TkRTX01BU1RFUl9UU0lHX0tFWQo="
  SIGNER_ADAPTER_DNS_INBOUND_REMOTE_IP: 192.168.99.5
  SIGNER_ADAPTER_DNS_INBOUND_REMOTE_PORT: "53"
  SIGNER_ADAPTER_DNS_OUTBOUND_PEER_IP: 192.168.99.10

