apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnssec-pv-claim-signer-customer-01
  namespace: customer-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
